name: GitHub Action - Pages
on: 
  push:
    branches: [ dev ]
jobs:
  Clone-GitHub-Repo:
    runs-on: ubuntu-latest
    steps:
      - run: echo " The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo " This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo " The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Git Clone Action
        run: git clone https://github.com/miixc/miixc.github.io.git
      - run: ls -a 
      - run: echo " The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo " The workflow is now ready to test your code on the runner."
      - run: git --version
      - run: git branch -a
      - run: git remote show origin
      - run: git fetch origin dev
      - run: git branch -a
      - run: git fetch origin pages
      - run: git checkout -b pages origin/pages
      - run: git merge dev
      - run: git push
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo " This job's status is ${{ job.status }}."
